import { type Character } from "../api/characters/type";

export interface TeamCharacter extends Character {
  status: 'Waiting' | 'Working'
}

export const team: TeamCharacter[] = [
  {
    name: 'Ares',
    skin: "men1",
    status: 'Waiting',
    mining_level: 0,
    mining_xp: 0,
    mining_max_xp: 0,
    woodcutting_level: 0,
    woodcutting_xp: 0,
    woodcutting_max_xp: 0,
    fishing_level: 0,
    fishing_xp: 0,
    fishing_max_xp: 0,
    weaponcrafting_level: 0,
    weaponcrafting_xp: 0,
    weaponcrafting_max_xp: 0,
    gearcrafting_level: 0,
    gearcrafting_xp: 0,
    gearcrafting_max_xp: 0,
    jewelrycrafting_level: 0,
    jewelrycrafting_xp: 0,
    jewelrycrafting_max_xp: 0,
    cooking_level: 0,
    cooking_xp: 0,
    cooking_max_xp: 0,
    alchemy_level: 0,
    alchemy_xp: 0,
    alchemy_max_xp: 0
  },
  {
    name: 'Athena',
    skin: 'women1',
    status: 'Waiting',
    mining_level: 0,
    mining_xp: 0,
    mining_max_xp: 0,
    woodcutting_level: 0,
    woodcutting_xp: 0,
    woodcutting_max_xp: 0,
    fishing_level: 0,
    fishing_xp: 0,
    fishing_max_xp: 0,
    weaponcrafting_level: 0,
    weaponcrafting_xp: 0,
    weaponcrafting_max_xp: 0,
    gearcrafting_level: 0,
    gearcrafting_xp: 0,
    gearcrafting_max_xp: 0,
    jewelrycrafting_level: 0,
    jewelrycrafting_xp: 0,
    jewelrycrafting_max_xp: 0,
    cooking_level: 0,
    cooking_xp: 0,
    cooking_max_xp: 0,
    alchemy_level: 0,
    alchemy_xp: 0,
    alchemy_max_xp: 0
  },
  {
    name: 'Hermes',
    skin: 'men2',
    status: 'Waiting',
    mining_level: 0,
    mining_xp: 0,
    mining_max_xp: 0,
    woodcutting_level: 0,
    woodcutting_xp: 0,
    woodcutting_max_xp: 0,
    fishing_level: 0,
    fishing_xp: 0,
    fishing_max_xp: 0,
    weaponcrafting_level: 0,
    weaponcrafting_xp: 0,
    weaponcrafting_max_xp: 0,
    gearcrafting_level: 0,
    gearcrafting_xp: 0,
    gearcrafting_max_xp: 0,
    jewelrycrafting_level: 0,
    jewelrycrafting_xp: 0,
    jewelrycrafting_max_xp: 0,
    cooking_level: 0,
    cooking_xp: 0,
    cooking_max_xp: 0,
    alchemy_level: 0,
    alchemy_xp: 0,
    alchemy_max_xp: 0
  },
  {
    name: 'Hades',
    skin: 'men3',
    status: 'Waiting',
    mining_level: 0,
    mining_xp: 0,
    mining_max_xp: 0,
    woodcutting_level: 0,
    woodcutting_xp: 0,
    woodcutting_max_xp: 0,
    fishing_level: 0,
    fishing_xp: 0,
    fishing_max_xp: 0,
    weaponcrafting_level: 0,
    weaponcrafting_xp: 0,
    weaponcrafting_max_xp: 0,
    gearcrafting_level: 0,
    gearcrafting_xp: 0,
    gearcrafting_max_xp: 0,
    jewelrycrafting_level: 0,
    jewelrycrafting_xp: 0,
    jewelrycrafting_max_xp: 0,
    cooking_level: 0,
    cooking_xp: 0,
    cooking_max_xp: 0,
    alchemy_level: 0,
    alchemy_xp: 0,
    alchemy_max_xp: 0
  },
];